import { getCurrentUser } from "@/lib/actions/user";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar";
import { rc } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Cinema App",
  description: "Generated by create next app",
};

export default async function RootLayout(props: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={rc(inter.className)}>
        {props.modal}
        {props.children}
      </body>
    </html>
  );
}
