import { getCurrentUser } from "@/lib/actions/user";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Cinema App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getCurrentUser();

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-[1280px] mx-auto">
          <Navbar user={user} />
          {children}
        </div>
      </body>
    </html>
  );
}
